/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuySmart;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Austin
 */
public class GUILoggedin extends javax.swing.JFrame {
private String choice1;
private String choice2;
public  static String purchasephone=null;

    /**
     * Creates new form GUI
     */
    public GUILoggedin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Phone1 = new javax.swing.JComboBox<>();
        Buy = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Helpbutton = new javax.swing.JButton();
        loginbutton = new javax.swing.JButton();
        Cartbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScreenTextArea = new javax.swing.JTextArea();
        Phone2 = new javax.swing.JComboBox<>();
        Comparebutton = new javax.swing.JButton();
        addtocartbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Phone1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iphone 8 64 GB", "Iphone 8 256 GB", "Iphone 8+ 64 GB", "Iphone 8+ 256 GB", "Iphone X 256 GB", "Iphone X 512 GB", "Iphone Xr 128 GB", "Iphone Xr 256 GB", "Iphone Xs 256 GB", "Iphone Xs 512 GB", "Iphone Xs Max 256 GB", "Iphone Xs Max 512 GB" }));
        Phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone1ActionPerformed(evt);
            }
        });

        Buy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iphone 8 64 GB", "Iphone 8 256 GB", "Iphone 8+ 64 GB", "Iphone 8+ 256 GB", "Iphone X 256 GB", "Iphone X 512 GB", "Iphone Xr 128 GB", "Iphone Xr 256 GB", "Iphone Xs 256 GB", "Iphone Xs 512 GB", "Iphone Xs Max 256 GB", "Iphone Xs Max 512 GB" }));
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Phone1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buy, 0, 136, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Buy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Welcome: Guest");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Helpbutton.setText("Help");
        Helpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpbuttonActionPerformed(evt);
            }
        });

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        Cartbutton.setText("Cart");
        Cartbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartbuttonActionPerformed(evt);
            }
        });

        ScreenTextArea.setEditable(false);
        ScreenTextArea.setColumns(20);
        ScreenTextArea.setRows(5);
        jScrollPane1.setViewportView(ScreenTextArea);
        Stock fillscreen = new Stock();
        try
        {
            fillscreen.fill();
        }catch (FileNotFoundException ex){}

        fillscreen.display(ScreenTextArea);

        Phone2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iphone 8 64 GB", "Iphone 8 256 GB", "Iphone 8+ 64 GB", "Iphone 8+ 256 GB", "Iphone X 256 GB", "Iphone X 512 GB", "Iphone Xr 128 GB", "Iphone Xr 256 GB", "Iphone Xs 256 GB", "Iphone Xs 512 GB", "Iphone Xs Max 256 GB", "Iphone Xs Max 512 GB" }));
        Phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone2ActionPerformed(evt);
            }
        });

        Comparebutton.setText("Compare");
        Comparebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComparebuttonActionPerformed(evt);
            }
        });

        addtocartbutton.setText("Add to Cart");
        addtocartbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cartbutton))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Comparebutton))
                            .addComponent(addtocartbutton))
                        .addGap(0, 397, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loginbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Helpbutton))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Helpbutton)
                            .addComponent(loginbutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cartbutton))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comparebutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addtocartbutton)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartbuttonActionPerformed
        dispose();
        CartGUI cart = new CartGUI();
        cart.setVisible(true);
        cart.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cart.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_CartbuttonActionPerformed

    private void Phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone1ActionPerformed
       JComboBox cb = (JComboBox)evt.getSource();
       choice1 = (String)cb.getSelectedItem();
       // TODO add your handling code here:
    }//GEN-LAST:event_Phone1ActionPerformed

    private void HelpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpbuttonActionPerformed
    JOptionPane.showMessageDialog(null, "For support please contact us at support@buysmart.ca");        // TODO add your handling code here:
    }//GEN-LAST:event_HelpbuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
    dispose();
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        login.pack();      // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void Phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone2ActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
       choice2 = (String)cb.getSelectedItem();
       // TODO add your handling code here:
    }//GEN-LAST:event_Phone2ActionPerformed

    private void ComparebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComparebuttonActionPerformed
      ScreenTextArea.setText(null);
      int i=0, j=0;
      Stock phone = new Stock();
        try {
        i = phone.findDevice(choice1);
        j = phone.findDevice(choice2);
        } catch (FileNotFoundException ex) {
        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        phone.displayAll(ScreenTextArea, i, j);
    }//GEN-LAST:event_ComparebuttonActionPerformed

    private void addtocartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "Item added to cart");
        dispose();
        CartGUI cart = new CartGUI();
        cart.setVisible(true);
        cart.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cart.pack();
    }//GEN-LAST:event_addtocartbuttonActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
    JComboBox cb = (JComboBox)evt.getSource();
    this.purchasephone = (String)cb.getSelectedItem();   
    }//GEN-LAST:event_BuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Buy;
    private javax.swing.JButton Cartbutton;
    private javax.swing.JButton Comparebutton;
    private javax.swing.JButton Helpbutton;
    private javax.swing.JComboBox<String> Phone1;
    private javax.swing.JComboBox<String> Phone2;
    private javax.swing.JTextArea ScreenTextArea;
    private javax.swing.JButton addtocartbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginbutton;
    // End of variables declaration//GEN-END:variables
}
